[package]
name = "node-manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.5.6"
toml = "0.5.9"
directories = "4.0.1"
ssh2 = "0.9.3"
crossterm = "0.25.0"